pipeline{
   agent any 
   tools{
    maven 'M2_HOME'
   }
   stages{
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:APA8jngacHb1ZgNkzguL49uL1Kx -T \
            target/bio*.jar \
             "http://ec2-54-87-244-84.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio"'
        }
    }
   }
}
